# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MCarlquist | Real Developer Struggles
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/recover" # the subpath of your site, e.g. /blog
url: "https://MCarlquist.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima theme settings
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/jekyll" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }

# SASS/SCSS configuration
sass:
  sass_dir: assets/scss
  style: expanded # Use expanded for development, compressed for production
  sourcemap: development # Enable source maps for development
  load_paths:
    - assets/scss
    - node_modules

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - "*.log"
  - README.md
  - .github/
  - .vscode/
  - .git/
  - .gitignore
  - assets/scss/_*.scss # Exclude SCSS partials from direct processing

# Include assets that should be processed
include:
  - assets/css/tailwind.css
  - assets/css/main.scss

# Asset processing configuration
defaults:
  - scope:
      path: "assets/css"
    values:
      sitemap: false

# Minification and optimization (for production)
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Development vs Production environment settings
# These can be overridden with JEKYLL_ENV environment variable
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Performance optimizations
incremental: true
profile: false

# CSS processing environment
environment: development # Override with JEKYLL_ENV=production for builds
